"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-14 16:28:26.114286
"""
import sqlalchemy as sa
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('portfolio_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_provider_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'provider', 'provider_type')
    )
    with op.batch_alter_table('category_provider_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_provider_types_category_id'), ['category_id'], unique=False)

    op.create_table('portfolio_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geocode_status', sa.Enum('not_needed', 'pending', 'succeeded', 'failed', name='geocode_status', native_enum=False, length=32), nullable=False),
    sa.Column('geocode_error', sa.Text(), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['portfolio_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_stores_upload_id'), ['upload_id'], unique=False)

    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'name')
    )
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_states_country_id'), ['country_id'], unique=False)

    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('boundary_south', sa.Float(), nullable=True),
    sa.Column('boundary_west', sa.Float(), nullable=True),
    sa.Column('boundary_north', sa.Float(), nullable=True),
    sa.Column('boundary_east', sa.Float(), nullable=True),
    sa.Column('boundary_source', sa.String(length=50), nullable=True),
    sa.Column('boundary_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_id', 'name')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_state_id'), ['state_id'], unique=False)

    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_upload_id', sa.Integer(), nullable=True),
    sa.Column('area_sq_km', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'geocoding', 'discovering', 'matching', 'completed', 'completed_with_errors', 'failed', name='market_status', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('south', sa.Float(), nullable=False),
    sa.Column('west', sa.Float(), nullable=False),
    sa.Column('north', sa.Float(), nullable=False),
    sa.Column('east', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['portfolio_upload_id'], ['portfolio_uploads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_markets_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_portfolio_upload_id'), ['portfolio_upload_id'], unique=False)

    op.create_table('discovered_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_place_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('provider_types', sa.JSON(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'provider', 'provider_place_id', name='uq_discovered_store_per_market')
    )
    with op.batch_alter_table('discovered_stores', schema=None) as batch_op:
        batch_op.create_index('ix_discovered_stores_market_category', ['market_id', 'category_id'], unique=False)

    op.create_table('discovery_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'completed_with_errors', 'failed', name='run_status', native_enum=False, length=32), nullable=False),
    sa.Column('geocode_attempted', sa.Integer(), nullable=False),
    sa.Column('geocode_failed', sa.Integer(), nullable=False),
    sa.Column('tiles_planned', sa.Integer(), nullable=False),
    sa.Column('tiles_completed', sa.Integer(), nullable=False),
    sa.Column('tiles_failed', sa.Integer(), nullable=False),
    sa.Column('provider_requests', sa.Integer(), nullable=False),
    sa.Column('places_returned', sa.Integer(), nullable=False),
    sa.Column('stores_saved', sa.Integer(), nullable=False),
    sa.Column('budget_exhausted', sa.Boolean(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovery_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_runs_market_id'), ['market_id'], unique=False)

    op.create_table('market_categories',
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('market_id', 'category_id')
    )
    op.create_table('market_portfolio_stores',
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_store_id', sa.Integer(), nullable=False),
    sa.Column('boundary_status', sa.Enum('inside', 'outside', 'unlocated', name='boundary_status', native_enum=False, length=32), nullable=False),
    sa.Column('matched_discovered_store_id', sa.Integer(), nullable=True),
    sa.Column('match_distance_m', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_discovered_store_id'], ['discovered_stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_store_id'], ['portfolio_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('market_id', 'portfolio_store_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_portfolio_stores')
    op.drop_table('market_categories')
    with op.batch_alter_table('discovery_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_runs_market_id'))

    op.drop_table('discovery_runs')
    with op.batch_alter_table('discovered_stores', schema=None) as batch_op:
        batch_op.drop_index('ix_discovered_stores_market_category')

    op.drop_table('discovered_stores')
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_markets_portfolio_upload_id'))
        batch_op.drop_index(batch_op.f('ix_markets_city_id'))

    op.drop_table('markets')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_state_id'))

    op.drop_table('cities')
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_states_country_id'))

    op.drop_table('states')
    with op.batch_alter_table('portfolio_stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_stores_upload_id'))

    op.drop_table('portfolio_stores')
    with op.batch_alter_table('category_provider_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_provider_types_category_id'))

    op.drop_table('category_provider_types')
    op.drop_table('portfolio_uploads')
    op.drop_table('countries')
    op.drop_table('categories')
    # ### end Alembic commands ###
